---
title: 'What are the changes in the new CBME curriculum '
author: "Kishore Puthezhath"
output:
  html_document:
    toc: true
    toc_float: true
date: '2020-08-08'
slug: CBME
categories: Medical education
tags: Academic
subtitle: ''
summary: ''
authors: []
lastmod: '2020-08-0 T23:14:20+05:30'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
bibliography: mypub.bib
csl: vancouver.csl
link-citations: yes
---

{{% callout note %}}
Excerpts of various modules for new CBME curriculum
{{% /callout %}}

### 1. What are the pros and cons of implementing integration into the CBME curriculum?

{{% alert note%}}
**Alignment** implies the teaching of subject material that occurs under a particular organ system/disease concept from the same phase in the same time frame i.e., temporally.  

**Integration** implies that concepts in a topic / organ system that are similar, overlapping or redundant are merged into a single teaching session in which subject based demarcations are removed.
{{% /alert %}}

#### Advantages

**Improved perception of the learning environment**
The integrated curriculum offers enjoyable learning experiences, leading to students’ satisfaction with the educational environment. A possible implication of this result is that the positive perception of the educational environment is associated with students’ improved perceptions of their quality of life, thereby increasing the likelihood of them achieving adequate learning development during medical school.  

**Reduced Students’ desertion** 
Integrated curriculum reform is useful for avoiding students’ desertion. Studies show that possibly because of the positive perception of the learning environment and the mentorships implemented in the preclinical phase, the over- all desertion rate declined from ~40% to 1.3% @hamza_process_2020.

#### Disadvantages  

**Resistance to curriculum reform**
“change without difference” in medical curriculum reforms can be attributed to the focus given for changing the curricular structure instead of examining the learning needs of the medical education community and transforming the curriculum based on these needs.

**Reduced students’ academic self-confidence**

The perceptions of students taught under the previous curriculum about differences between both curricula included that the reformed curriculum had less learning quality than their own. This perception could have undermined the self-confidence in learning of the students studying the current curriculum, even though they had good grades. 

### 2. What are the different methods of skills training?

|Domain|Assessment method|
|-|-|
|Intellectual|SNAPPS, OMP, Reflections, Metacognition|
|Psychomotor|Peyton's 4 step|
|Communication|Kalamazoo declaration framework|
Table: Methods of skill training
 
### 3. What are the modifications in formative and summative assessment in the new curriculum? 

Major characteristics of competency based assessment are their 

+ longitudinal nature, 
+ provision of developmental feedback and 
+ authentic settings, 

all of which **result in lowering the stakes on individual assessments**. This has other important implications also for assessment design. Since the stakes are low and purpose is to improve learning, high standardization and psychometric rigor is not required. Authenticity of assessment task is more important than its structure or objectivity. Expert subjective judgment plays a major role in assessment of competencies.

Traditional assessments are easy to design, administer, score and analyse compared to CBA but may not be able to provide complete information about the stage of the student. 

{{% callout note %}}
Traditional assessments are snap shot observations of learning, are generally not linked to instructions or outcomes and promote test taking behaviour. They are fragmented and mainly focus on knowledge.
{{% /callout %}} 

CBA, on the other hand, provides more comprehensive information about not only the current stage of the student but also about his progression and ascendency. They are longitudinal, often with low stakes and help to reduce examination anxiety. CBA is based on direct observation and therefore helps in generation of authentic feedback, which helps the students to learn better. This process of assessment for learning is crucial for the acquisition of competencies.


 
### 4. What is the importance of log book in the new UG curriculum?

{{% callout note %}}
Logbook: is a verified record of the progression of the learner documenting the acquisition of the requisite knowledge, skills, attitude and/ or competencies.
{{% /callout %}}

A key aspect of the new Competency Based UG Curriculum is the emphasis on acquisition of competencies as a requisite for progression in the course. Active learning process by the student and his/her progression to achievement of competencies / pre- determined tasks need to be documented. A record of activities completed and competencies acquired is necessary to ensure that the learner has acquired the key competencies. The logbook forms an integral part of the formative / continuous assessment program.

### References
 