---
title: 'CBME-Building evidence in India '
author: "Kishore Puthezhath"
output:
  html_document:
    toc: true
    toc_float: true
date: '2020-01-28'
slug: Building evidence
categories: Medical education
tags: Academic
subtitle: ''
summary: ''
authors: []
lastmod: '2020-01-28 T23:14:20+05:30'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
bibliography: mypub.bib
csl: vancouver.csl
link-citations: yes
---

{{% callout note %}}
Building evidence in India for CBME
{{% /callout %}}

Recently, I revisited  various modules of the new undergraduate CBME curriculum for completing the assignments of the Advanced course in medical education. It became  clearer to me that the  objective of the CBME is to prepare students for clinical practice. Hence, the focus is on knowledge application and not on knowledge gain, whether it is foundation course or electives module. To achieve this, the learning has to be made contextual. The greatest obstacle in the implementation is **resistance to change**, and the most convincing question behind that is <font color="emerald">where is the evidence?</font>

Policy decisions regarding education should ideally be based on the available evidence in the literature. However, many a time evidence, though available, is not in context to Indian scenario. For example, it was interesting  to see that most of the reference articles mentioned in the **Further reading** section of the new modules are western. I am not telling that there are no articles from our country, but their number and content are limited. 

With the new CBME curriculum and the flexibility it has given to the faculty members, there is a scope for innovations in teaching–learning methods and assessment. Responsibility lies with the faculty members to plan studies whenever they are trying something new in their own settings and generate accurate and reliable data. Sharing of findings and experiences of such studies would lead to the building up of educational literature for our country and help the administrators/decision-makers to decide what works in our country or what needs modification before drafting any educational policy @regeCompetencybasedLearningMedical2020. 

### References
 